name: Release

on:
    workflow_call:
        inputs:
            bump:
                description: 'Bump version by semver keyword.'
                type: string
                required: true
            bump-rust:
                description: 'Bump Rust version.'
                type: boolean
                required: true
            bump-typescript:
                description: 'Bump TypeScript version.'
                type: boolean
                required: true
            bump-typescript-tool:
                description: 'TypeScript tool to use for bumping (`lerna` or `npm`).'
                type: string
                required: false
                default: 'lerna'
            extract-version:
                description: 'Version to extract (`rust` or `typescript`).'
                type: string
                required: true

            # Inputs for `actions-rust-lang/setup-rust-toolchain`.
            # https://github.com/actions-rust-lang/setup-rust-toolchain/blob/main/action.yml
            toolchain:
                description: 'Comma-separated list of Rust toolchain specifications. Last version becomes the default. -- see https://rust-lang.github.io/rustup/concepts/toolchains.html#toolchain-specification'
                type: string
                required: false
            target:
                description: 'Target triple to install for this toolchain'
                type: string
                required: false
        secrets:
            app-client-id:
                description: 'GitHub App Client ID.'
                required: true
            app-private-key:
                description: 'GitHub App private key.'
                required: true

permissions:
    contents: write

jobs:
    release:
        name: Release
        runs-on: ubuntu-latest

        steps:
            - name: Generate GitHub App token
              id: app-token
              uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
              with:
                  client-id: ${{ secrets.app-client-id }}
                  private-key: ${{ secrets.app-private-key }}

            - name: Checkout
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

            - name: Set up Rust toolchain
              if: ${{ inputs.bump-rust }}
              uses: actions-rust-lang/setup-rust-toolchain@46268bd060767258de96ed93c1251119784f2ab6 # v1.16.1
              with:
                  toolchain: ${{ inputs.toolchain }}
                  target: ${{ inputs.target }}

            - name: Install Cargo Binary Install
              if: ${{ inputs.bump-rust }}
              uses: cargo-bins/cargo-binstall@aaa84a43aec4955a42c5ffc65d258961e39f276e # v1.19.1

            - name: Install crates
              if: ${{ inputs.bump-rust }}
              run: cargo binstall --force -y cargo-workspaces toml-cli

            - name: Bump Rust version
              if: ${{ inputs.bump-rust }}
              run: cargo workspaces version --all --no-git-commit --yes ${{ inputs.bump }}

            - name: Extract Rust version
              if: ${{ inputs.extract-version == 'rust' }}
              id: extract-rust-version
              run: echo "VERSION=v$(toml get Cargo.toml workspace.package.version --raw)" >> "$GITHUB_OUTPUT"

            - name: Set up Node.js
              if: ${{ inputs.bump-typescript }}
              uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
              with:
                  node-version: 'lts/*'
                  cache: 'npm'

            - name: Install dependencies
              if: ${{ inputs.bump-typescript }}
              run: npm ci

            - name: Bump TypeScript version
              if: ${{ inputs.bump-typescript }}
              env:
                  TOOL: ${{ case(inputs.bump-typescript-tool == 'lerna', 'npx lerna', 'npm') }}
              run: $TOOL version --no-git-tag-version --yes ${{ inputs.bump }}

            - name: Extract TypeScript version
              if: ${{ inputs.extract-version == 'typescript' }}
              id: extract-typescript-version
              env:
                  FILE: ${{ case(inputs.bump-typescript-tool == 'lerna', 'lerna', 'package') }}
              run: echo "VERSION=v$(jq -r .version ./$FILE.json)" >> "$GITHUB_OUTPUT"

            - name: Format with Prettier
              if: ${{ inputs.extract-version == 'typescript' }}
              run: npx prettier --write .

            - name: Version
              id: version
              env:
                  VERSION: |-
                      ${{ case(
                        inputs.extract-version == 'rust', steps.extract-rust-version.outputs.VERSION,
                        inputs.extract-version == 'typescript', steps.extract-typescript-version.outputs.VERSION,
                        ''
                      ) }}
              run: test -n "$VERSION" && echo "VERSION=$VERSION" >> "$GITHUB_OUTPUT"

            - name: Add changes
              run: git add .

            - name: Commit
              id: commit
              uses: dsanders11/github-app-commit-action@2bbcd331016d8c950b05a24b56e7eb9cb50d545e # v2.1.0
              with:
                  message: ${{ steps.version.outputs.VERSION }}
                  token: ${{ steps.app-token.outputs.token }}

            - name: Reset and pull
              run: git reset --hard && git pull

            - name: Tag
              uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
              env:
                  GIT_TAG: ${{ steps.version.outputs.VERSION }}
                  GIT_SHA: ${{ steps.commit.outputs.sha }}
              with:
                  script: |
                      github.rest.git.createRef({
                          owner: context.repo.owner,
                          repo: context.repo.repo,
                          ref: `refs/tags/${process.env.GIT_TAG}`,
                          sha: process.env.GIT_SHA
                      })

            - name: Release
              uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda # v3.0.0
              with:
                  generate_release_notes: true
                  make_latest: true
                  tag_name: ${{ steps.version.outputs.VERSION }}
                  token: ${{ steps.app-token.outputs.token }}
