name: Rust

on:
    workflow_call:
        inputs:
            if:
                description: Whether to run the jobs.
                type: boolean
                required: false
                default: true
            runs-on:
                description: The type of machine to run the job on.
                type: string
                required: false
                default: ubuntu-latest

            enable-lint:
                description: Enable lint job.
                type: boolean
                required: false
                default: true
            enable-format:
                description: Enable format job.
                type: boolean
                required: false
                default: true
            enable-dependencies:
                description: Enable dependencies job.
                type: boolean
                required: false
                default: true
            enable-test:
                description: Enable test job.
                type: boolean
                required: false
                default: true

            # Inputs for `actions-rust-lang/setup-rust-toolchain`.
            # https://github.com/actions-rust-lang/setup-rust-toolchain/blob/main/action.yml
            toolchain:
                description: 'Comma-separated list of Rust toolchain specifications. Last version becomes the default. -- see https://rust-lang.github.io/rustup/concepts/toolchains.html#toolchain-specification'
                type: string
                required: false
            target:
                description: 'Target triple to install for this toolchain'
                type: string
                required: false

permissions:
    contents: read

jobs:
    lint:
        name: Lint
        if: ${{ inputs.if && inputs.enable-lint }}
        runs-on: ${{ inputs.runs-on }}

        steps:
            - name: Checkout
              uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

            - name: Set up Rust toolchain
              uses: actions-rust-lang/setup-rust-toolchain@46268bd060767258de96ed93c1251119784f2ab6 # v1.16.1
              with:
                  toolchain: ${{ inputs.toolchain }}
                  target: ${{ inputs.target }}
                  components: clippy

            - name: Lint
              run: cargo clippy --all-features --all-targets --locked

    format:
        name: Format
        if: ${{ inputs.if && inputs.enable-format }}
        runs-on: ${{ inputs.runs-on }}

        steps:
            - name: Checkout
              uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

            - name: Set up Rust toolchain
              uses: actions-rust-lang/setup-rust-toolchain@46268bd060767258de96ed93c1251119784f2ab6 # v1.16.1
              with:
                  toolchain: ${{ inputs.toolchain }}
                  target: ${{ inputs.target }}
                  components: rustfmt

            - name: Install Cargo Binary Install
              uses: cargo-bins/cargo-binstall@aaa84a43aec4955a42c5ffc65d258961e39f276e # v1.19.1

            - name: Install crates
              run: cargo binstall -y --force cargo-sort

            - name: Check manifest formatting
              run: cargo sort --workspace --check

            - name: Check formatting
              run: cargo fmt --all --check

    dependencies:
        name: Dependencies
        if: ${{ inputs.if && inputs.enable-dependencies }}
        runs-on: ${{ inputs.runs-on }}

        steps:
            - name: Checkout
              uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

            - name: Set up Rust toolchain
              uses: actions-rust-lang/setup-rust-toolchain@46268bd060767258de96ed93c1251119784f2ab6 # v1.16.1
              with:
                  toolchain: ${{ inputs.toolchain }}
                  target: ${{ inputs.target }}

            - name: Install Cargo Binary Install
              uses: cargo-bins/cargo-binstall@aaa84a43aec4955a42c5ffc65d258961e39f276e # v1.19.1

            - name: Install crates
              run: cargo binstall -y --force cargo-deny cargo-machete

            - name: Check dependencies
              run: cargo deny check

            - name: Check unused dependencies
              run: cargo machete --with-metadata

    test:
        name: Test
        if: ${{ inputs.if && inputs.enable-test }}
        runs-on: ${{ inputs.runs-on }}

        steps:
            - name: Checkout
              uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

            - name: Set up Rust toolchain
              uses: actions-rust-lang/setup-rust-toolchain@46268bd060767258de96ed93c1251119784f2ab6 # v1.16.1
              with:
                  toolchain: ${{ inputs.toolchain }}
                  target: ${{ inputs.target }}
                  components: rust-src

            - name: Test
              run: cargo test --all-features --locked --release
